apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-v2nf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-v2nf@sha256:9a1747305552d256ba65231065f4f402b8a7395ec82ae497426443cb5c786ece
        name: my-nodejs
        resources: {}
status: {}
